### ISSUE TITLE
get_templates ignores filters

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/piex#5]
* D3M Pipeline Explorer version: 0.1.1
* Python version: 3.6.2
* Operating System: Ubuntu 16.04.5 LTS

### Description

I expect `ex.get_templates(data_type='image')` to return only template for images, but it returns all templates. Looking at the source, `**filters` is unused.

Furthermore, it is confusing that `ex.get_templates` returns `data_type` as a column whereas `ex.get_datasets` and `ex.get_pipelines` return `data_modality` as a column. There are probably other name mismatches.

**Comment by csala** [comment]
Fixed in v0.2.0
